# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - bulkpro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Ensure startup.sh is executable
        run: chmod +x startup.sh  # Make sure startup script has execution permission

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*  # No need to add startup.sh explicitly, it's already included

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/



deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7099E632A84451EA32862CBEAB97D8F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB7F03B97CB34A9A956D4F5DEFADBD68 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E18A2C5962D9486D81412B9BD9A37906 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bulkpro'
          slot-name: 'Production'
          this is ,y current pipleine code and this is startup.sh code #!/bin/bash
# Start Node.js authentication proxy in the background on port 8000
cd proxy
node proxy.mjs --port=8000 &

# Start Streamlit app on port 8501
cd ..
streamlit run app.py --server.port=8501 --server.enableCORS=false
