name: Build and deploy Python app to Azure Web App - bulkpro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Run tests here (PyTest, Django test suites, etc.)

      - name: Ensure startup.sh exists and is executable
        run: |
          if [ ! -f startup.sh ]; then
            echo "Error: startup.sh not found!"
            exit 1
          fi
          chmod +x startup.sh  # Ensure it's executable

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*  

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Verify startup.sh exists
        run: |
          if [ ! -f startup.sh ]; then
            echo "Error: startup.sh not found after unzipping!"
            exit 1
          fi
          chmod +x startup.sh  # Ensure it's executable

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7099E632A84451EA32862CBEAB97D8F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB7F03B97CB34A9A956D4F5DEFADBD68 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E18A2C5962D9486D81412B9BD9A37906 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bulkpro'
          slot-name: 'Production'

      - name: Run Startup Script
        run: ./startup.sh
